"""empty message

Revision ID: 2094d7d7b54d
Revises: 4c8a9f2a30fd
Create Date: 2018-10-13 23:06:27.553724

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = '2094d7d7b54d'
down_revision = '4c8a9f2a30fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pawikan_nest_evaluation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('pawikan_nest_evaluation', sa.Column('nest_evaluation_type_id', sa.Integer(), nullable=False))
    op.add_column('pawikan_nest_evaluation', sa.Column('num_eggs_u', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pawikan_nest_evaluation', 'pawikan_nest_evaluation_type', ['nest_evaluation_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pawikan_nest_evaluation', type_='foreignkey')
    op.drop_column('pawikan_nest_evaluation', 'num_eggs_u')
    op.drop_column('pawikan_nest_evaluation', 'nest_evaluation_type_id')
    op.drop_table('pawikan_nest_evaluation_type')
    # ### end Alembic commands ###
