"""empty message

Revision ID: 37c46382b946
Revises: 4740f538bda2
Create Date: 2018-10-07 18:31:26.064778

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '37c46382b946'
down_revision = '4740f538bda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pawikan_encounter_encounter_type_id_fkey', 'pawikan_encounter', type_='foreignkey')
    op.drop_column('pawikan_encounter', 'encounter_type_id')
    op.drop_column('pawikan_encounter_version', 'encounter_type_id')
    op.drop_table('pawikan_encounter_type')
    conn = op.get_bind()
    md = sa.MetaData(bind=conn)
    tab = sa.Table('pawikan_encounter_picture', md, autoload=True)
    conn.execute(tab.delete())
    tab = sa.Table('pawikan_encounter', md, autoload=True)
    conn.execute(tab.delete())
    enum = postgresql.ENUM('Stranding', 'Fisheries bycatch', 'Nesting', name='encounter_type')
    enum.create(op.get_bind())
    op.add_column('pawikan_encounter', sa.Column('encounter_type', sa.Enum('Stranding', 'Fisheries bycatch', 'Nesting', name='encounter_type'), nullable=False))
    op.add_column('pawikan_encounter_version', sa.Column('encounter_type', sa.Enum('Stranding', 'Fisheries bycatch', 'Nesting', name='encounter_type'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pawikan_encounter_version', 'encounter_type')
    op.drop_column('pawikan_encounter', 'encounter_type')
    op.create_table('pawikan_encounter_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pawikan_encounter_type_pkey'),
    sa.UniqueConstraint('name', name='pawikan_encounter_type_name_key')
    )
    op.add_column('pawikan_encounter_version', sa.Column('encounter_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pawikan_encounter', sa.Column('encounter_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('pawikan_encounter_encounter_type_id_fkey', 'pawikan_encounter', 'pawikan_encounter_type', ['encounter_type_id'], ['id'])
    # ### end Alembic commands ###
