"""empty message

Revision ID: 432df06c95f6
Revises: b43b00369183
Create Date: 2018-04-15 14:02:52.585700

"""
from alembic import op
import sqlalchemy as sa
from flask_appbuilder.models.mixins import ImageColumn


# revision identifiers, used by Alembic.
revision = '432df06c95f6'
down_revision = 'b43b00369183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'observation_picture',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('picture', ImageColumn(size=(2048, 2048, False),
                                         thumbnail_size=(800, 800, True)),
                  nullable=True),
        sa.Column('observation_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['observation_id'], ['base_observation.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_picture')
    # ### end Alembic commands ###
