"""empty message

Revision ID: 4740f538bda2
Revises: ebf5a730f346
Create Date: 2018-10-07 18:09:23.268430

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4740f538bda2'
down_revision = 'ebf5a730f346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pawikan_stranding_version_end_transaction_id', table_name='pawikan_stranding_version')
    op.drop_index('ix_pawikan_stranding_version_operation_type', table_name='pawikan_stranding_version')
    op.drop_index('ix_pawikan_stranding_version_transaction_id', table_name='pawikan_stranding_version')
    op.drop_constraint('pawikan_stranding_sex_id_fkey', 'pawikan_stranding', type_='foreignkey')
    op.drop_constraint('pawikan_stranding_species_id_fkey', 'pawikan_stranding', type_='foreignkey')
    op.drop_constraint('pawikan_stranding_id_fkey', 'pawikan_stranding', type_='foreignkey')
    op.drop_column('pawikan_stranding', 'species_id')
    op.drop_column('pawikan_stranding', 'ccl')
    op.drop_column('pawikan_stranding', 'location')
    op.drop_column('pawikan_stranding', 'sex_id')
    op.drop_table('pawikan_stranding_species')
    op.drop_table('pawikan_stranding_version')
    op.drop_table('pawikan_stranding_picture')

    conn = op.get_bind()
    md = sa.MetaData(bind=conn)
    tab = sa.Table('pawikan_stranding', md, autoload=True)
    conn.execute(
        tab.delete()
    )

    op.add_column('pawikan_stranding', sa.Column('alive', sa.Boolean(), nullable=False))
    op.add_column('pawikan_stranding', sa.Column('observation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pawikan_stranding', 'pawikan_encounter', ['observation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pawikan_stranding', sa.Column('sex_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pawikan_stranding', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=True))
    op.add_column('pawikan_stranding', sa.Column('ccl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pawikan_stranding', sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pawikan_stranding', type_='foreignkey')
    op.create_foreign_key('pawikan_stranding_id_fkey', 'pawikan_stranding', 'base_observation', ['id'], ['id'])
    op.create_foreign_key('pawikan_stranding_species_id_fkey', 'pawikan_stranding', 'pawikan_stranding_species', ['species_id'], ['id'])
    op.create_foreign_key('pawikan_stranding_sex_id_fkey', 'pawikan_stranding', 'sex', ['sex_id'], ['id'])
    op.drop_column('pawikan_stranding', 'observation_id')
    op.drop_column('pawikan_stranding', 'alive')
    op.create_table('pawikan_stranding_picture',
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('changed_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stranding_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], name='pawikan_stranding_picture_changed_by_fk_fkey'),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], name='pawikan_stranding_picture_created_by_fk_fkey'),
    sa.ForeignKeyConstraint(['stranding_id'], ['pawikan_stranding.id'], name='pawikan_stranding_picture_stranding_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pawikan_stranding_picture_pkey')
    )
    op.create_table('pawikan_stranding_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('species_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ccl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sex_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='pawikan_stranding_version_pkey')
    )
    op.create_index('ix_pawikan_stranding_version_transaction_id', 'pawikan_stranding_version', ['transaction_id'], unique=False)
    op.create_index('ix_pawikan_stranding_version_operation_type', 'pawikan_stranding_version', ['operation_type'], unique=False)
    op.create_index('ix_pawikan_stranding_version_end_transaction_id', 'pawikan_stranding_version', ['end_transaction_id'], unique=False)
    op.create_table('pawikan_stranding_species',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('genus', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('species', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('common_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pawikan_stranding_species_pkey')
    )
    # ### end Alembic commands ###
