"""empty message

Revision ID: 4c8a9f2a30fd
Revises: d4aaa1d6666f
Create Date: 2018-10-13 16:29:06.738277

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = '4c8a9f2a30fd'
down_revision = 'd4aaa1d6666f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('DELETE FROM pawikan_fisheries_interaction CASCADE')
    op.execute('DELETE FROM pawikan_in_water CASCADE')
    op.execute('DELETE FROM pawikan_stranding CASCADE')
    op.execute('DELETE FROM pawikan_hatchlings CASCADE')
    op.execute('DELETE FROM pawikan_nest_with_egg CASCADE')
    op.execute('DELETE FROM pawikan_trade_exhibit CASCADE')
    op.execute('DELETE FROM pawikan_nest_evaluation CASCADE')
    op.execute('DELETE FROM pawikan_tagging CASCADE')
    op.execute('DELETE FROM pawikan_general_picture CASCADE')
    op.execute('DELETE FROM pawikan_general CASCADE')
    op.execute('DELETE FROM pawikan_facility_encountered CASCADE')
    op.execute('DELETE FROM pawikan_fishing_gear CASCADE')
    op.execute('DELETE FROM pawikan_fishing_turtle_condition CASCADE')
    op.execute('DELETE FROM pawikan_fishing_turtle_disposition CASCADE')
    op.execute('DELETE FROM pawikan_hatchling_disposition CASCADE')
    op.execute('DELETE FROM pawikan_hatchling_location CASCADE')
    op.execute('DELETE FROM pawikan_inwater_activity_type CASCADE')
    op.execute('DELETE FROM pawikan_inwater_turtle_activity CASCADE')
    op.execute('DELETE FROM pawikan_inwater_type CASCADE')
    op.execute('DELETE FROM pawikan_location_type CASCADE')
    op.execute('DELETE FROM pawikan_nest_type CASCADE')
    op.execute('DELETE FROM pawikan_nesting_action_taken CASCADE')
    op.execute('DELETE FROM pawikan_trade_exhibit_type CASCADE')
    op.execute('DELETE FROM pawikan_trade_turtle_condition CASCADE')
    op.execute('DELETE FROM pawikan_trade_turtle_disposition CASCADE')
    op.execute('DELETE FROM pawikan_species CASCADE')

    op.create_unique_constraint('pawikan_facility_encountered_name_key', 'pawikan_facility_encountered', ['name'])
    op.create_unique_constraint('pawikan_fishing_gear_name_key', 'pawikan_fishing_gear', ['name'])
    op.create_unique_constraint('pawikan_fishing_turtle_condition_name_key', 'pawikan_fishing_turtle_condition', ['name'])
    op.create_unique_constraint('pawikan_fishing_turtle_disposition_name_key', 'pawikan_fishing_turtle_disposition', ['name'])
    op.create_unique_constraint('pawikan_hatchling_disposition_name_key', 'pawikan_hatchling_disposition', ['name'])
    op.create_unique_constraint('pawikan_hatchling_location_name_key', 'pawikan_hatchling_location', ['name'])
    op.create_unique_constraint('pawikan_inwater_activity_type_name_key', 'pawikan_inwater_activity_type', ['name'])
    op.create_unique_constraint('pawikan_inwater_turtle_activity_name_key', 'pawikan_inwater_turtle_activity', ['name'])
    op.create_unique_constraint('pawikan_inwater_type_name_key', 'pawikan_inwater_type', ['name'])
    op.create_unique_constraint('pawikan_location_type_name_key', 'pawikan_location_type', ['name'])
    op.create_unique_constraint('pawikan_nest_type_name_key', 'pawikan_nest_type', ['name'])
    op.create_unique_constraint('pawikan_nesting_action_taken_name_key', 'pawikan_nesting_action_taken', ['name'])
    op.create_unique_constraint('pawikan_trade_exhibit_type_name_key', 'pawikan_trade_exhibit_type', ['name'])
    op.create_unique_constraint('pawikan_trade_turtle_condition_name_key', 'pawikan_trade_turtle_condition', ['name'])
    op.create_unique_constraint('pawikan_trade_turtle_disposition_name_key', 'pawikan_trade_turtle_disposition', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pawikan_facility_encountered_name_key', 'pawikan_facility_encountered', type_='unique')
    op.drop_constraint('pawikan_fishing_gear_name_key', 'pawikan_fishing_gear', type_='unique')
    op.drop_constraint('pawikan_fishing_turtle_condition_name_key', 'pawikan_fishing_turtle_condition', type_='unique')
    op.drop_constraint('pawikan_fishing_turtle_disposition_name_key', 'pawikan_fishing_turtle_disposition', type_='unique')
    op.drop_constraint('pawikan_hatchling_disposition_name_key', 'pawikan_hatchling_disposition', type_='unique')
    op.drop_constraint('pawikan_hatchling_location_name_key', 'pawikan_hatchling_location', type_='unique')
    op.drop_constraint('pawikan_inwater_activity_type_name_key', 'pawikan_inwater_activity_type', type_='unique')
    op.drop_constraint('pawikan_inwater_turtle_activity_name_key', 'pawikan_inwater_turtle_activity', type_='unique')
    op.drop_constraint('pawikan_inwater_type_name_key', 'pawikan_inwater_type', type_='unique')
    op.drop_constraint('pawikan_location_type_name_key', 'pawikan_location_type', type_='unique')
    op.drop_constraint('pawikan_nest_type_name_key', 'pawikan_nest_type', type_='unique')
    op.drop_constraint('pawikan_nesting_action_taken_name_key', 'pawikan_nesting_action_taken', type_='unique')
    op.drop_constraint('pawikan_trade_exhibit_type_name_key', 'pawikan_trade_exhibit_type', type_='unique')
    op.drop_constraint('pawikan_trade_turtle_condition_name_key', 'pawikan_trade_turtle_condition', type_='unique')
    op.drop_constraint('pawikan_trade_turtle_disposition_name_key', 'pawikan_trade_turtle_disposition', type_='unique')
    # ### end Alembic commands ###
