"""empty message

Revision ID: 55a9a611b848
Revises: 728de49e17bb
Create Date: 2018-04-15 14:45:48.389410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column, select
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = '55a9a611b848'
down_revision = '728de49e17bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the columns with nullable=True
    op.add_column('pawikan_encounter_picture',
                  sa.Column('changed_by_fk', sa.Integer(), nullable=True))
    op.add_column('pawikan_encounter_picture',
                  sa.Column('changed_on', sa.DateTime(), nullable=True))
    op.add_column('pawikan_encounter_picture',
                  sa.Column('created_by_fk', sa.Integer(), nullable=True))
    op.add_column('pawikan_encounter_picture',
                  sa.Column('created_on', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'pawikan_encounter_picture',
                          'ab_user', ['changed_by_fk'], ['id'])
    op.create_foreign_key(None, 'pawikan_encounter_picture',
                          'ab_user', ['created_by_fk'], ['id'])

    # Get default values for user and datetime columns
    utab = table('ab_user', column('id'))
    tab = table('pawikan_encounter_picture',
                column('changed_on'), column('changed_by_fk'),
                column('created_on'), column('created_by_fk'))
    now = datetime.now(timezone.utc)
    conn = op.get_bind()
    uid = conn.execute(
        select([utab.c.id]).order_by(utab.c.id)).fetchone()['id']

    # Set default values for user and datetime columns
    op.execute(tab.update().values(changed_on=now, created_on=now,
                                   changed_by_fk=uid, created_by_fk=uid))

    # Set columns to not nullable
    op.alter_column('pawikan_encounter_picture', 'changed_on', nullable=False)
    op.alter_column('pawikan_encounter_picture', 'changed_by_fk',
                    nullable=False)
    op.alter_column('pawikan_encounter_picture', 'created_by_fk',
                    nullable=False)
    op.alter_column('pawikan_encounter_picture', 'created_on', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pawikan_encounter_picture', type_='foreignkey')
    op.drop_constraint(None, 'pawikan_encounter_picture', type_='foreignkey')
    op.drop_column('pawikan_encounter_picture', 'created_on')
    op.drop_column('pawikan_encounter_picture', 'created_by_fk')
    op.drop_column('pawikan_encounter_picture', 'changed_on')
    op.drop_column('pawikan_encounter_picture', 'changed_by_fk')
    # ### end Alembic commands ###
