"""empty message

Revision ID: 728de49e17bb
Revises: 432df06c95f6
Create Date: 2018-04-15 14:36:36.698799

"""
from alembic import op
import sqlalchemy as sa
from flask_appbuilder.models.mixins import ImageColumn


# revision identifiers, used by Alembic.
revision = '728de49e17bb'
down_revision = '432df06c95f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pawikan_encounter_picture',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('picture', ImageColumn(size=(2048, 2048, False),
                                         thumbnail_size=(800, 800, True)),
                  nullable=True),
        sa.Column('encounter_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['encounter_id'], ['pawikan_encounter.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('observation_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pawikan_encounter_picture')
    op.create_table(
        'observation_picture',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('picture', ImageColumn(size=(2048, 2048, False),
                                         thumbnail_size=(800, 800, True)),
                  nullable=True),
        sa.Column('observation_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['observation_id'], ['base_observation.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
