"""empty message

Revision ID: 73adb7498a4f
Revises: ca615d6f4a8c
Create Date: 2018-10-14 12:35:18.518923

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = '73adb7498a4f'
down_revision = 'ca615d6f4a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pawikan_general', 'lateral_scutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pawikan_general', 'prefrontal_scutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pawikan_general', 'prefrontal_scutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pawikan_general', 'lateral_scutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
