"""empty message

Revision ID: 810275fb090c
Revises: 55a9a611b848
Create Date: 2018-04-21 00:08:42.067548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810275fb090c'
down_revision = '55a9a611b848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dataset_pkey'),
    sa.UniqueConstraint('module', name='dataset_module_key'),
    sa.UniqueConstraint('name', name='dataset_name_key')
    )
    # ### end Alembic commands ###
