"""empty message

Revision ID: 81ea744238e4
Revises: 
Create Date: 2018-04-15 00:20:52.645906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ea744238e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pawikan_encounter_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pawikan_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('base_observation',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('observation_datetime', sa.DateTime(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('dataset', sa.String(length=50), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['observer_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pawikan_encounter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('encounter_type_id', sa.Integer(), nullable=True),
    sa.Column('ccl', sa.Numeric(), nullable=True),
    sa.Column('sex_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_type_id'], ['pawikan_encounter_type.id'], ),
    sa.ForeignKeyConstraint(['id'], ['base_observation.id'], ),
    sa.ForeignKeyConstraint(['sex_id'], ['sex.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pawikan_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pawikan_encounter')
    op.drop_table('base_observation')
    op.drop_table('sex')
    op.drop_table('pawikan_species')
    op.drop_table('pawikan_encounter_type')
    op.drop_table('dataset')
    # ### end Alembic commands ###
