"""empty message

Revision ID: 93bb40148399
Revises: c692c276bdb2
Create Date: 2018-10-13 15:59:37.833158

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = '93bb40148399'
down_revision = 'c692c276bdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pawikan_nest_with_egg', sa.Column('nester_observed', sa.Enum('yes', 'no', name='pawikanyesnoenum'), nullable=False, server_default='no'))
    op.alter_column('pawikan_nest_with_egg', 'nester_observed', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pawikan_nest_with_egg', 'nester_observed')
    # ### end Alembic commands ###
