"""empty message

Revision ID: b43b00369183
Revises: 81ea744238e4
Create Date: 2018-04-15 12:42:19.779535

"""
from alembic import op
import sqlalchemy as sa
from flask_appbuilder.models.mixins import ImageColumn


# revision identifiers, used by Alembic.
revision = 'b43b00369183'
down_revision = '81ea744238e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pawikan_species', sa.Column('description', sa.Text(),
                                               nullable=True))
    op.add_column('pawikan_species', sa.Column('picture', ImageColumn(
        size=(800, 800, True), thumbnail_size=(100, 100, True)
    ), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pawikan_species', 'picture')
    op.drop_column('pawikan_species', 'description')
    # ### end Alembic commands ###
