"""empty message

Revision ID: b710c03a8922
Revises: 2de084f83244
Create Date: 2018-09-23 10:13:16.895445

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = 'b710c03a8922'
down_revision = '2de084f83244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pawikan_stranding_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('picture', flask_appbuilder.models.mixins.ImageColumn(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pawikan_stranding_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('species_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('ccl', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('sex_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_pawikan_stranding_version_end_transaction_id'), 'pawikan_stranding_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_pawikan_stranding_version_operation_type'), 'pawikan_stranding_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_pawikan_stranding_version_transaction_id'), 'pawikan_stranding_version', ['transaction_id'], unique=False)
    op.create_table('pawikan_stranding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('ccl', sa.Integer(), nullable=True),
    sa.Column('sex_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['base_observation.id'], ),
    sa.ForeignKeyConstraint(['sex_id'], ['sex.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pawikan_stranding_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pawikan_stranding_picture',
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('changed_on', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picture', flask_appbuilder.models.mixins.ImageColumn(), nullable=True),
    sa.Column('stranding_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_fk', sa.Integer(), nullable=False),
    sa.Column('created_by_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], ['ab_user.id'], ),
    sa.ForeignKeyConstraint(['stranding_id'], ['pawikan_stranding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_pawikan_encounter_location', table_name='pawikan_encounter')
    op.drop_index('idx_pawikan_encounter_version_location', table_name='pawikan_encounter_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pawikan_encounter_version_location', 'pawikan_encounter_version', ['location'], unique=False)
    op.create_index('idx_pawikan_encounter_location', 'pawikan_encounter', ['location'], unique=False)
    op.drop_table('pawikan_stranding_picture')
    op.drop_table('pawikan_stranding')
    op.drop_index(op.f('ix_pawikan_stranding_version_transaction_id'), table_name='pawikan_stranding_version')
    op.drop_index(op.f('ix_pawikan_stranding_version_operation_type'), table_name='pawikan_stranding_version')
    op.drop_index(op.f('ix_pawikan_stranding_version_end_transaction_id'), table_name='pawikan_stranding_version')
    op.drop_table('pawikan_stranding_version')
    op.drop_table('pawikan_stranding_species')
    # ### end Alembic commands ###
