"""empty message

Revision ID: ebf5a730f346
Revises: 3c28e9c94706
Create Date: 2018-09-29 10:27:30.680883

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = 'ebf5a730f346'
down_revision = '3c28e9c94706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('base_observation', sa.Column('reporter_contact',
                                                sa.String(length=255),
                                                nullable=True))
    conn = op.get_bind()
    md = sa.MetaData(bind=conn)
    tab = sa.Table('base_observation', md, autoload=True)
    conn.execute(
        tab.update()
        .where(tab.c.reporter == None)
        .values(reporter='unkown'))
    conn.execute(
        tab.update()
        .where(tab.c.reporter_contact == None)
        .values(reporter_contact='unkown'))

    op.alter_column('base_observation',
                    'reporter_contact', nullable=False)
    op.alter_column('base_observation', 'reporter',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_observation', 'reporter',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_column('base_observation', 'reporter_contact')
    # ### end Alembic commands ###
