"""empty message

Revision ID: f8e4603be726
Revises: 73adb7498a4f
Create Date: 2018-10-16 14:20:54.478775

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import flask_appbuilder


# revision identifiers, used by Alembic.
revision = 'f8e4603be726'
down_revision = '73adb7498a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pawikan_general', sa.Column('barangay_id', sa.Integer()))
    op.create_foreign_key(None, 'pawikan_general', 'barangay', ['barangay_id'], ['id'])
    op.add_column('pawikan_general_version', sa.Column('barangay_id', sa.Integer(), autoincrement=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pawikan_general_barangay_id_fkey', 'pawikan_general',
                       type_='foreignkey')
    op.drop_column('pawikan_general_version', 'barangay_id')
    op.drop_column('pawikan_general', 'barangay_id')
    # ### end Alembic commands ###
